# Generated by Django 3.1.7 on 2021-03-19 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название чата')),
                ('create_date', models.DateField(null=True, verbose_name='Дата создания')),
                ('private', models.BooleanField(default=True, verbose_name='Приватный чат')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Сообщение')),
                ('date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chat.chat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='FriendshipRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='Статус отношений')),
                ('seen', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('user_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_action', to=settings.AUTH_USER_MODEL)),
                ('user_friend_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_one_friend', to=settings.AUTH_USER_MODEL)),
                ('user_friend_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_two_friend', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_chat_users', to='chat.chat')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователи чатов',
                'verbose_name_plural': 'Пользователи чатов',
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='', max_length=100, verbose_name='Статус')),
                ('birthday', models.DateField(null=True, verbose_name='День рождения')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Additional information of user',
                'verbose_name_plural': 'Additional information of user',
            },
        ),
        migrations.AddConstraint(
            model_name='friendshiprelations',
            constraint=models.UniqueConstraint(fields=('user_friend_one', 'user_friend_two'), name='unique_constraint_friends'),
        ),
        migrations.AddConstraint(
            model_name='friendshiprelations',
            constraint=models.CheckConstraint(check=models.Q(user_friend_two__gt=django.db.models.expressions.F('user_friend_one')), name='user_friend_one > user_friend_two'),
        ),
    ]
